#pragma once
// P stands for position([])
#define P_Q LT4
#define P_W LT3
#define P_F LT2
#define P_P LT1
#define P_G LT0
#define P_J RT0
#define P_L RT1
#define P_U RT2
#define P_Y RT3
#define P_SEMICOLON RT4
#define P_A LM4
#define P_R LM3
#define P_S LM2
#define P_T LM1
#define P_D LM0
#define P_H RM0
#define P_N RM1
#define P_E RM2
#define P_I RM3
#define P_O RM4
#define P_Z LB4
#define P_X LB3
#define P_C LB2
#define P_V LB1
#define P_B LB0
#define P_K RB0
#define P_M RB1
#define P_COMMA RB2
#define P_DOT RB3
#define P_SLASH RB4
